## SNOMED CT(v.1.2.2)

In [44]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/snomed-ct-entity-challenge/train_annotations.csv')
df

,annotation_id,note_id,start,end,span,concept_id,annotation_type
0,1,10043750-DS-6,180.0,198.0,No Known Allergies,609328004,test
1,2,10043750-DS-6,201.0,223.0,Adverse Drug Reactions,419511003,test
2,3,10043750-DS-6,263.0,275.0,colon cancer,363406005,test
3,4,10043750-DS-6,321.0,336.0,right colectomy,359571009,test
4,5,10043750-DS-6,393.0,399.0,clinic,737492002,test
...,...,...,...,...,...,...,...
75486,265076,11532659-DS-11,10592.0,10606.0,hemoperitoneum,45626005,proposed_ACCEPTED
75487,265078,10860165-DS-24,6894.0,6910.0,hemopneumothorax,16632002,proposed_ACCEPTED
75488,265229,13227028-DS-12,3373.0,3389.0,intraparenchymal,449020009,proposed_ACCEPTED
75489,265266,11714071-DS-56,5982.0,5985.0,jaw,661005,proposed_ACCEPTED
75490,266274,16991646-DS-11,1030.0,1043.0,shoulder pain,45326000,proposed_ACCEPTED

In [45]:
df = df.rename(columns={'concept_id': 'entity_code'})
df

,annotation_id,note_id,start,end,span,entity_code,annotation_type
0,1,10043750-DS-6,180.0,198.0,No Known Allergies,609328004,test
1,2,10043750-DS-6,201.0,223.0,Adverse Drug Reactions,419511003,test
2,3,10043750-DS-6,263.0,275.0,colon cancer,363406005,test
3,4,10043750-DS-6,321.0,336.0,right colectomy,359571009,test
4,5,10043750-DS-6,393.0,399.0,clinic,737492002,test
...,...,...,...,...,...,...,...
75486,265076,11532659-DS-11,10592.0,10606.0,hemoperitoneum,45626005,proposed_ACCEPTED
75487,265078,10860165-DS-24,6894.0,6910.0,hemopneumothorax,16632002,proposed_ACCEPTED
75488,265229,13227028-DS-12,3373.0,3389.0,intraparenchymal,449020009,proposed_ACCEPTED
75489,265266,11714071-DS-56,5982.0,5985.0,jaw,661005,proposed_ACCEPTED
75490,266274,16991646-DS-11,1030.0,1043.0,shoulder pain,45326000,proposed_ACCEPTED

In [46]:
import os

from elasticsearch import Elasticsearch

ES_SERVER_HOST = os.getenv("ES_SERVER_HOST", "3.35.110.161")
ES_SERVER_PORT = int(os.getenv("ES_SERVER_PORT", "9200"))
ES_SERVER_USERNAME = os.getenv("ES_SERVER_USERNAME", "elastic")
ES_SERVER_PASSWORD = os.getenv("ES_SERVER_PASSWORD", "snomed")


es_client = Elasticsearch(
    f"http://{ES_SERVER_HOST}:{ES_SERVER_PORT}",
    basic_auth=(ES_SERVER_USERNAME, ES_SERVER_PASSWORD),
    request_timeout=60,
)

In [47]:
import warnings

import pandas as pd
from tqdm import tqdm


def map_snomed_to_omop_es(input_df: pd.DataFrame) -> pd.DataFrame:
    """
    DataFrame의 'entity_code'를 사용하여 Elasticsearch 'concept-small' 인덱스를 조회하고,
    OMOP concept_id, concept_name, domain_id를 병합합니다.

    Args:
        input_df (pd.DataFrame): 'note_id', 'note_text', 'entity_name', 'entity_code' 포함

    Returns:
        pd.DataFrame: 'concept_id', 'concept_name', 'domain_id'가 추가된 DataFrame
    """

    # 2. 고유한 entity_code 추출 (ES 조회의 효율성을 위해)
    # 'entity_code'를 문자열로 변환 (ES term 쿼리 및 merge를 위해)
    try:
        input_df["entity_code"] = input_df["entity_code"].astype(str)
    except Exception as e:
        print(f"[오류] 'entity_code'를 문자열로 변환 중 오류: {e}")
        # NaN이나 비정상 값이 있는지 확인 필요
        input_df = input_df.dropna(subset=["entity_code"])
        input_df["entity_code"] = input_df["entity_code"].astype(int).astype(str)

    unique_codes = input_df["entity_code"].unique()
    print(f"\n--- 2. 고유 entity_code 추출 완료 ---")
    print(f"원본 {len(input_df)}건 -> 고유 코드 {len(unique_codes)}건")

    # 3. ES 조회 및 매핑 테이블 생성
    print(f"\n--- 3. ES 인덱스 'concept-small' 조회 중 ---")
    snomed_to_omop_map = {}

    for code in tqdm(unique_codes, desc="Mapping SNOMED codes"):
        # ES 쿼리 정의
        query_body = {
            "query": {
                "bool": {
                    "filter": [
                        {"term": {"vocabulary_id": "SNOMED"}},
                        {"term": {"concept_code": code}},
                        # 'concept_code'가 'keyword' 타입으로 매핑되어 있어야 함
                    ]
                }
            },
            "_source": [
                "concept_id",
                "concept_name",
                "domain_id",
                "standard_concept",
            ],  # 표준 여부도 확인
            "size": 1,  # concept_code + vocabulary_id는 고유해야 함
        }

        try:
            response = es_client.search(index="concept-small", body=query_body)
            hits = response["hits"]["hits"]

            if hits:
                # 직접 매핑된 컨셉 (Standard 또는 Non-Standard일 수 있음)
                source_concept = hits[0]["_source"]

                # 여기서는 사용자의 요청(직접 조회)을 그대로 따릅니다.
                snomed_to_omop_map[code] = {
                    "concept_id": source_concept.get("concept_id"),
                    "concept_name": source_concept.get("concept_name"),
                    "domain_id": source_concept.get("domain_id"),
                }
            else:
                # ES에서 코드를 찾지 못한 경우
                snomed_to_omop_map[code] = {
                    "concept_id": None,
                    "concept_name": None,
                    "domain_id": None,
                }
        except Exception as e:
            print(f"ES 조회 중 오류 (Code: {code}): {e}")
            snomed_to_omop_map[code] = {
                "concept_id": None,
                "concept_name": None,
                "domain_id": None,
            }

    print("ES 조회 및 매핑 테이블 생성 완료.")

    # 4. 매핑 딕셔너리를 DataFrame으로 변환
    print("\n--- 4. 매핑 테이블 -> DataFrame 변환 ---")
    omop_df = pd.DataFrame.from_dict(snomed_to_omop_map, orient="index")
    omop_df = omop_df.reset_index().rename(columns={"index": "entity_code"})

    # entity_code를 merge를 위해 문자열 타입으로 유지
    omop_df["entity_code"] = omop_df["entity_code"].astype(str)

    # 5. 원본 DataFrame과 매핑된 OMOP 정보 병합
    print("\n--- 5. 원본 DataFrame과 병합 (Left Join) ---")
    final_df = pd.merge(input_df, omop_df, on="entity_code", how="left")

    print("병합 완료! 최종 데이터프레임 생성.")
    return final_df


# --- 스크립트 실행 ---
if __name__ == "__main__":
    if "df" in locals() or "df" in globals():
        print("--- 'df' 변수 확인됨 ---")
        final_mapped_df = map_snomed_to_omop_es(df)

        print("\n\n--- 최종 매핑 결과 (상위 10개) ---")
        print(final_mapped_df.head(10))

        print("\n\n--- 매핑 실패 (None) 건수 확인 ---")
        print(
            final_mapped_df["concept_id"].isna().sum(),
            "건의 매핑 실패 (ES에서 찾을 수 없음)",
        )

    else:
        print("[주의] 'mapping_test_df' 변수가 존재하지 않습니다.")
        print("이 스크립트를 단독으로 실행한 경우, 테스트용 더미 데이터를 사용하거나")
        print("이전 단계의 'create_mapping_test_set()' 함수를 먼저 실행해야 합니다.")

--- 'df' 변수 확인됨 ---

--- 2. 고유 entity_code 추출 완료 ---
원본 75491건 -> 고유 코드 6595건

--- 3. ES 인덱스 'concept-small' 조회 중 ---

Mapping SNOMED codes:   0%|          | 0/6595 [00:00<?, ?it/s]

Mapping SNOMED codes: 100%|██████████| 6595/6595 [06:23<00:00, 17.21it/s]

ES 조회 및 매핑 테이블 생성 완료.

--- 4. 매핑 테이블 -> DataFrame 변환 ---

--- 5. 원본 DataFrame과 병합 (Left Join) ---
병합 완료! 최종 데이터프레임 생성.


--- 최종 매핑 결과 (상위 10개) ---
   annotation_id        note_id  start    end                    span  \
0              1  10043750-DS-6  180.0  198.0      No Known Allergies
1              2  10043750-DS-6  201.0  223.0  Adverse Drug Reactions
2              3  10043750-DS-6  263.0  275.0            colon cancer
3              4  10043750-DS-6  321.0  336.0         right colectomy
4              5  10043750-DS-6  393.0  399.0                  clinic
5              6  10043750-DS-6  426.0  439.0            colon cancer
6              7  10043750-DS-6  472.0  483.0             colonoscopy
7              8  10043750-DS-6  504.0  516.0            cecal cancer
8              9  10043750-DS-6  526.0  540.0          investigations
9             10  10043750-DS-6  558.0  576.0      metastatic disease

  entity_code annotation_type concept_id  \
0   609328004            test   43530807
1   419511003            test    4305025
2   363406005            test    4180790
3   359571009            test    4233412
4   737492002            test   42537845
5   363406005            test    4180790
6    73761001            test    4249893
7   363350007            test     443391
8   386053000            test    4297090
9   128462008            test     432851

                              concept_name    domain_id
0                     allergic disposition  Observation
1  propensity to adverse reactions to drug  Observation
2                 malignant tumor of colon    Condition
3                          right colectomy    Procedure
4               outpatient care management    Procedure
5                 malignant tumor of colon    Condition
6                              colonoscopy    Procedure
7                 malignant tumor of cecum    Condition
8                     evaluation procedure    Procedure
9            metastatic malignant neoplasm    Condition


--- 매핑 실패 (None) 건수 확인 ---
0 건의 매핑 실패 (ES에서 찾을 수 없음)

In [48]:
final_mapped_df = final_mapped_df.drop(columns=["annotation_id", "start", "end", "entity_code", "annotation_type"])
final_mapped_df

,note_id,span,concept_id,concept_name,domain_id
0,10043750-DS-6,No Known Allergies,43530807,allergic disposition,Observation
1,10043750-DS-6,Adverse Drug Reactions,4305025,propensity to adverse reactions to drug,Observation
2,10043750-DS-6,colon cancer,4180790,malignant tumor of colon,Condition
3,10043750-DS-6,right colectomy,4233412,right colectomy,Procedure
4,10043750-DS-6,clinic,42537845,outpatient care management,Procedure
...,...,...,...,...,...
75486,11532659-DS-11,hemoperitoneum,194690,nontraumatic hemoperitoneum,Condition
75487,10860165-DS-24,hemopneumothorax,4042409,hemopneumothorax,Condition
75488,13227028-DS-12,intraparenchymal,40492969,intraparenchymal hemorrhage of brain,Condition
75489,11714071-DS-56,jaw,4281237,jaw region structure,Spec Anatomic Site
75490,16991646-DS-11,shoulder pain,4166666,pain of shoulder region,Condition

In [49]:
final_mapped_df = final_mapped_df.rename(columns={'span': 'entity_name'})
final_mapped_df.head()

,note_id,entity_name,concept_id,concept_name,domain_id
0,10043750-DS-6,No Known Allergies,43530807,allergic disposition,Observation
1,10043750-DS-6,Adverse Drug Reactions,4305025,propensity to adverse reactions to drug,Observation
2,10043750-DS-6,colon cancer,4180790,malignant tumor of colon,Condition
3,10043750-DS-6,right colectomy,4233412,right colectomy,Procedure
4,10043750-DS-6,clinic,42537845,outpatient care management,Procedure

In [9]:
final_mapped_df['concept_id'].unique()

array(['43530807', '4305025', '4180790', ..., '602851', '4107785',
       '4046477'], dtype=object)

In [16]:
final_mapped_df[final_mapped_df['concept_id'] == '43530807']

,note_id,entity_name,concept_id,concept_name,domain_id
0,10043750-DS-6,No Known Allergies,43530807,allergic disposition,Observation
5681,11532659-DS-11,No Known Allergies,43530807,allergic disposition,Observation
6351,11576109-DS-15,No Known Allergies,43530807,allergic disposition,Observation
9623,12050253-DS-20,allergy,43530807,allergic disposition,Observation
9666,12128814-DS-15,No Known Allergies,43530807,allergic disposition,Observation
11286,12549331-DS-3,No Known Allergies,43530807,allergic disposition,Observation
12185,12626414-DS-32,No Known Allergies,43530807,allergic disposition,Observation
12804,12962702-DS-14,No Known Allergies,43530807,allergic disposition,Observation
18949,16393593-DS-5,No Known Allergies,43530807,allergic disposition,Observation
19888,16991646-DS-11,No Known Allergies,43530807,allergic disposition,Observation
21058,18046197-DS-13,allergy,43530807,allergic disposition,Observation
22214,18752997-DS-9,ALLERGY,43530807,allergic disposition,Observation
27079,10807423-DS-19,No Known Allergies,43530807,allergic disposition,Observation
27231,10813665-DS-7,No Known Allergies,43530807,allergic disposition,Observation
28407,10938537-DS-20,No Known Allergies,43530807,allergic disposition,Observation
32469,11417242-DS-18,No Known Allergies,43530807,allergic disposition,Observation
33670,11524757-DS-4,No Known Allergies,43530807,allergic disposition,Observation
34909,11714071-DS-56,allergy,43530807,allergic disposition,Observation
34912,11714071-DS-56,allergy,43530807,allergic disposition,Observation
40305,12290802-DS-3,No Known Allergies,43530807,allergic disposition,Observation
42805,12515572-DS-13,No Known Allergies,43530807,allergic disposition,Observation
45496,12880467-DS-7,No Known Allergies,43530807,allergic disposition,Observation
45779,12969257-DS-11,No Known Allergies,43530807,allergic disposition,Observation
46932,13030379-DS-26,allergy,43530807,allergic disposition,Observation
47701,13220371-DS-18,allergy,43530807,allergic disposition,Observation
47742,13340544-DS-6,No Known Allergies,43530807,allergic disposition,Observation
48453,13491166-DS-21,No Known Allergies,43530807,allergic disposition,Observation
48962,13859166-DS-19,No Known Allergies,43530807,allergic disposition,Observation
51877,14652764-DS-17,No Known Allergies,43530807,allergic disposition,Observation
52169,14757896-DS-11,No Known Allergies,43530807,allergic disposition,Observation
52610,14809657-DS-15,No Known Allergies,43530807,allergic disposition,Observation
53652,15242970-DS-15,No Known Allergies,43530807,allergic disposition,Observation
56448,15618038-DS-10,No Known Allergies,43530807,allergic disposition,Observation
58131,15993000-DS-9,No Known Allergies,43530807,allergic disposition,Observation
61862,17327209-DS-5,No Known Allergies,43530807,allergic disposition,Observation
63018,17665522-DS-2,No Known Allergies,43530807,allergic disposition,Observation
64223,18039514-DS-11,No Known Allergies,43530807,allergic disposition,Observation
66371,18568215-DS-21,No Known Allergies,43530807,allergic disposition,Observation
67993,18806799-DS-5,No Known Allergies,43530807,allergic disposition,Observation
69174,18928863-DS-19,No Known Allergies,43530807,allergic disposition,Observation
70147,19073967-DS-22,No Known Allergies,43530807,allergic disposition,Observation
71173,19301098-DS-6,No Known Allergies,43530807,allergic disposition,Observation
71783,19442119-DS-15,No Known Allergies,43530807,allergic disposition,Observation
72772,19658009-DS-19,No Known Allergies,43530807,allergic disposition,Observation

In [50]:
dedup_df = final_mapped_df.drop_duplicates(subset=['concept_id', 'entity_name'])
len(dedup_df)

16531

In [51]:
dedup_df[dedup_df['concept_id'] == '43530807']

,note_id,entity_name,concept_id,concept_name,domain_id
0,10043750-DS-6,No Known Allergies,43530807,allergic disposition,Observation
9623,12050253-DS-20,allergy,43530807,allergic disposition,Observation
22214,18752997-DS-9,ALLERGY,43530807,allergic disposition,Observation

In [52]:
dedup_df = dedup_df[dedup_df['domain_id'] != 'Spec Anatomic Site']
dedup_df['domain_id'].unique()

array(['Observation', 'Condition', 'Procedure', 'Measurement'],
      dtype=object)

In [53]:
dedup_df = dedup_df.reset_index(drop=True)
dedup_df

,note_id,entity_name,concept_id,concept_name,domain_id
0,10043750-DS-6,No Known Allergies,43530807,allergic disposition,Observation
1,10043750-DS-6,Adverse Drug Reactions,4305025,propensity to adverse reactions to drug,Observation
2,10043750-DS-6,colon cancer,4180790,malignant tumor of colon,Condition
3,10043750-DS-6,right colectomy,4233412,right colectomy,Procedure
4,10043750-DS-6,clinic,42537845,outpatient care management,Procedure
...,...,...,...,...,...
13989,19926965-DS-14,skip,4107785,does skip,Observation
13990,19926965-DS-14,deep breathing exercises,4046477,deep breathing exercises,Procedure
13991,10653756-DS-22,exercise stress test,4261794,electrocardiogram with exercise test,Measurement
13992,12970259-DS-4,NaN,4208938,blood sodium measurement (procedure),Measurement
13993,13220371-DS-18,poor po intake,4275273,decrease in appetite,Observation

In [54]:
dedup_df.to_csv("/Users/rose/omop-mapper/data/snomed-mapping-data-2602.csv", index=False)

In [2]:
import pandas as pd

# CSV 로드
df = pd.read_csv('/Users/rose/omop-mapper/data/snomed-mapping-data-2602.csv')

# entity_name에서 줄바꿈 제거 (\n, \r, \r\n 등)
df['entity_name'] = df['entity_name'].astype(str).str.replace(r'[\r\n]+', ' ', regex=True).str.strip()

# 여러 공백을 하나로 정리
df['entity_name'] = df['entity_name'].str.replace(r'\s+', ' ', regex=True)

In [3]:
# 줄바꿈 제거 후 CSV로 저장
df.to_csv('/Users/rose/omop-mapper/data/snomed-mapping-data-2602.csv', index=False)

## SNUH(coverage90)

In [55]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/MapOMOP_test_data_coverage90_concept_id.csv')
df

,record_count,domain_id,source_value,source_code,concept_id,cumulative_record_count,total_record_count
0,7399,Condition,Gynecomastia,D00014430,4168447,85375132,94863350
1,7407,Condition,lung disease,75538,257907,85367733,94863350
2,7410,Condition,"Genu valgum, acquired",D00012970,80504,85360326,94863350
3,7411,Condition,Basal ganglia hemorrhage,D00009963,4112018,85352916,94863350
4,7412,Condition,"Ankylosing spondylitis, lumbar region",D00023451,4035614,85345505,94863350
...,...,...,...,...,...,...,...
2923,94305864,Measurement,HR,1021,3027018,285293665,2670570628
2924,95477521,Measurement,DBP,1013,3012888,190987801,2670570628
2925,95477521,Measurement,"difficulty, writing",1013,3012888,190987801,2670570628
2926,95510280,Measurement,"difficulty, weaning",1012,3004249,95510280,2670570628
2927,95510280,Measurement,SBP,1012,3004249,95510280,2670570628

In [58]:
df = df.drop(columns=["record_count", "cumulative_record_count", "total_record_count"])
df

,domain_id,source_value,source_code,concept_id
0,Condition,Gynecomastia,D00014430,4168447
1,Condition,lung disease,75538,257907
2,Condition,"Genu valgum, acquired",D00012970,80504
3,Condition,Basal ganglia hemorrhage,D00009963,4112018
4,Condition,"Ankylosing spondylitis, lumbar region",D00023451,4035614
...,...,...,...,...
2923,Measurement,HR,1021,3027018
2924,Measurement,DBP,1013,3012888
2925,Measurement,"difficulty, writing",1013,3012888
2926,Measurement,"difficulty, weaning",1012,3004249
2927,Measurement,SBP,1012,3004249

In [60]:
from tqdm import tqdm

# concept_id를 문자열이 아닌 정수로 조회해야 할 수 있으므로 확인
unique_ids = df["concept_id"].unique()
print(f"고유 concept_id: {len(unique_ids)}건")

id_to_name = {}

for cid in tqdm(unique_ids, desc="Fetching concept_name"):
    query_body = {
        "query": {
            "term": {"concept_id": int(cid)}
        },
        "_source": ["concept_name"],
        "size": 1
    }
    try:
        response = es_client.search(index="concept-small", body=query_body)
        hits = response["hits"]["hits"]
        if hits:
            id_to_name[cid] = hits[0]["_source"].get("concept_name")
        else:
            id_to_name[cid] = None
    except Exception as e:
        print(f"오류 (concept_id: {cid}): {e}")
        id_to_name[cid] = None

df["concept_name"] = df["concept_id"].map(id_to_name)
print(f"매핑 완료. 실패: {df['concept_name'].isna().sum()}건")
df.head()

고유 concept_id: 2836건

Fetching concept_name: 100%|██████████| 2836/2836 [00:45<00:00, 62.09it/s]

매핑 완료. 실패: 4건

,domain_id,source_value,source_code,concept_id,concept_name
0,Condition,Gynecomastia,D00014430,4168447,gynecomastia
1,Condition,lung disease,75538,257907,disorder of lung
2,Condition,"Genu valgum, acquired",D00012970,80504,acquired genu valgum
3,Condition,Basal ganglia hemorrhage,D00009963,4112018,basal ganglia hemorrhage
4,Condition,"Ankylosing spondylitis, lumbar region",D00023451,4035614,ankylosing spondylitis with organ / system inv...

In [63]:
df = df.dropna(subset=['concept_name'])

In [65]:
df = df.drop_duplicates(subset=['source_value', 'concept_id']).reset_index(drop=True)
df

,domain_id,source_value,source_code,concept_id,concept_name
0,Condition,Gynecomastia,D00014430,4168447,gynecomastia
1,Condition,lung disease,75538,257907,disorder of lung
2,Condition,"Genu valgum, acquired",D00012970,80504,acquired genu valgum
3,Condition,Basal ganglia hemorrhage,D00009963,4112018,basal ganglia hemorrhage
4,Condition,"Ankylosing spondylitis, lumbar region",D00023451,4035614,ankylosing spondylitis with organ / system inv...
...,...,...,...,...,...
2919,Measurement,HR,1021,3027018,heart rate
2920,Measurement,DBP,1013,3012888,diastolic blood pressure
2921,Measurement,"difficulty, writing",1013,3012888,diastolic blood pressure
2922,Measurement,"difficulty, weaning",1012,3004249,systolic blood pressure
2923,Measurement,SBP,1012,3004249,systolic blood pressure

In [72]:
df = df[df['domain_id'] != 'Observation'].reset_index(drop=True)

In [73]:
len(df)

2923

In [74]:
df.to_csv("/Users/rose/omop-mapper/data/MapOMOP_test_data_coverage90_concept_id.csv", index=False)

## Baseline_snuh

In [1]:
import pandas as pd

df = pd.read_excel("/Users/rose/omop-mapper/data/old/Baseline_mapping_snuh_20260224_134426.xlsx")
df

,index,baseline,source_value,domain_id,concept_id,concept_name
0,1,1,Gynecomastia,Condition,4168447,gynecomastia
1,2,1,lung disease,Condition,257907,disorder of lung
2,3,1,"Genu valgum, acquired",Condition,80504,acquired genu valgum
3,4,1,Basal ganglia hemorrhage,Condition,4112018,basal ganglia hemorrhage
4,5,1,"Ankylosing spondylitis, lumbar region",Condition,4035614,ankylosing spondylitis with organ / system inv...
...,...,...,...,...,...,...
2918,2919,5,HR,Measurement,3027018,heart rate
2919,2920,5,DBP,Measurement,3012888,diastolic blood pressure
2920,2921,entity:주호소/ground truth concept:임상관찰,"difficulty, writing",Measurement,3012888,diastolic blood pressure
2921,2922,entity:주호소/ground truth concept:임상관찰,"difficulty, weaning",Measurement,3004249,systolic blood pressure
2922,2923,5,SBP,Measurement,3004249,systolic blood pressure

In [6]:
df['baseline'].unique()

array([1, 9, 0, 5, '한국어 불가', 'brand name',
       'entity:ICD10코드명/ground truth concept:약제',
       'entity:Provider/ground truth concept:약제',
       'entity:주호소/ground truth concept:임상관찰'], dtype=object)

In [7]:
df_filtered = df[
    (df['baseline'] == 0) | 
    (df['baseline'] == '한국어 불가')
].copy()

In [8]:
df_filtered['baseline'].unique()

array([0, '한국어 불가'], dtype=object)

In [9]:
df_filtered.to_csv("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv", index=False)

In [1]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/MapOMOP_test_data_coverage90_final.csv')
df

,domain_id,source_value,concept_id
0,Condition,Corneal erosion,4179918
1,Drug_exposure,Mupirocin 2% 10g ointment,43771785
2,Drug_exposure,Normal saline(NaCl 0.9%) 10mL Prefilled syringe,19127213
3,Drug_exposure,Anastrozole 1mg tab,1348267
4,Condition,Ebstein anomaly,4069182
...,...,...,...
2723,Condition,spinal stenosis of lumbar spine,136788
2724,Condition,"Unruptured aneurysm, middle cerebral artery (M...",37204668
2725,Condition,Ewing sarcoma,4144193
2726,Drug_exposure,Smoflipid* 20% 100ml inj,43187068
2727,Condition,gastroenteritis,4101468

In [4]:
df.loc[df['domain_id'] == 'Drug_exposure', 'domain_id'] = 'Drug'
df

      domain_id                                       source_value  concept_id
0     Condition                                    Corneal erosion     4179918
1          Drug                          Mupirocin 2% 10g ointment    43771785
2          Drug    Normal saline(NaCl 0.9%) 10mL Prefilled syringe    19127213
3          Drug                                Anastrozole 1mg tab     1348267
4     Condition                                    Ebstein anomaly     4069182
...         ...                                                ...         ...
2723  Condition                    spinal stenosis of lumbar spine      136788
2724  Condition  Unruptured aneurysm, middle cerebral artery (M...    37204668
2725  Condition                                      Ewing sarcoma     4144193
2726       Drug                           Smoflipid* 20% 100ml inj    43187068
2727  Condition                                    gastroenteritis     4101468

[2728 rows x 3 columns]

In [23]:
import sys
from pathlib import Path

# 프로젝트 루트 찾기 (test 폴더에서 실행 시 상위로)
_root = Path.cwd().resolve()
if _root.name == "test":
    _root = _root.parent
sys.path.insert(0, str(_root / "src"))
sys.path.insert(0, str(_root))

In [10]:
from tqdm import tqdm
from src.MapOMOP.elasticsearch_client import ElasticsearchClient

# Elasticsearch 클라이언트 생성
es_client = ElasticsearchClient.create_default()

# concept_id로 concept_name 조회 (중복 제거해 한 번만 조회)
unique_ids = df["concept_id"].dropna().unique()
print(f"고유 concept_id: {len(unique_ids)}건")

id_to_name = {}
for cid in tqdm(unique_ids, desc="Fetching concept_name"):
    query_body = {
        "query": {"term": {"concept_id": str(cid)}},  # keyword 타입이므로 str 사용
        "_source": ["concept_name"],
        "size": 1
    }
    try:
        response = es_client.es_client.search(index="concept-small", body=query_body)
        hits = response["hits"]["hits"]
        if hits:
            id_to_name[cid] = hits[0]["_source"].get("concept_name")
        else:
            id_to_name[cid] = None
    except Exception as e:
        print(f"오류 (concept_id: {cid}): {e}")
        id_to_name[cid] = None

# 마지막 열 옆에 concept_name 추가
df["concept_name"] = df["concept_id"].map(id_to_name)
print(f"매핑 완료. 실패: {df['concept_name'].isna().sum()}건")
df.head()

/opt/homebrew/Caskroom/miniconda/base/envs/mapomop/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

고유 concept_id: 2640건

Fetching concept_name: 100%|██████████| 2640/2640 [00:35<00:00, 74.18it/s]

매핑 완료. 실패: 1건

,domain_id,source_value,concept_id,concept_name
0,Condition,Corneal erosion,4179918,corneal erosion
1,Drug,Mupirocin 2% 10g ointment,43771785,10000 mg mupirocin 0.02 mg/mg topical ointment
2,Drug,Normal saline(NaCl 0.9%) 10mL Prefilled syringe,19127213,10 ml sodium chloride 9 mg/ml prefilled syringe
3,Drug,Anastrozole 1mg tab,1348267,anastrozole 1 mg oral tablet
4,Condition,Ebstein anomaly,4069182,ebstein's anomaly

In [12]:
df[df['concept_name'].isna()]

    domain_id  source_value  concept_id concept_name
907      Drug  Trestan* cap  2001000036         None

In [15]:
df.to_csv("/Users/rose/omop-mapper/data/MapOMOP_test_data_coverage90_final.csv", index=False)

In [24]:
import pandas as pd

df = pd.read_excel('/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.xlsx', sheet_name='final_검토추가')
df

,domain_id,entity_name,ground_truth_concept_id,검토내용
0,Condition,Esophageal varix without bleeding,22340,NaN
1,Condition,Chronic tonsillitis,23220,NaN
2,Condition,Neck pain,24134,NaN
3,Condition,Hypoglycemia,24609,NaN
4,Condition,acute tonsilitis,24660,NaN
...,...,...,...,...
3146,Drug_exposure,Midazolam 5mg/5mL inj,46287620,NaN
3147,Drug_exposure,Trestan* cap,2001000036,NaN
3148,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN
3149,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN
3150,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN

In [25]:
df.loc[df['domain_id'] == 'Drug_exposure', 'domain_id'] = 'Drug'
df

,domain_id,entity_name,ground_truth_concept_id,검토내용
0,Condition,Esophageal varix without bleeding,22340,NaN
1,Condition,Chronic tonsillitis,23220,NaN
2,Condition,Neck pain,24134,NaN
3,Condition,Hypoglycemia,24609,NaN
4,Condition,acute tonsilitis,24660,NaN
...,...,...,...,...
3146,Drug,Midazolam 5mg/5mL inj,46287620,NaN
3147,Drug,Trestan* cap,2001000036,NaN
3148,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN
3149,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN
3150,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN

In [26]:
df = df.rename(columns={
    "entity_name": "source_value",
    "ground_truth_concept_id": "concept_id",
    "검토내용": "review"
})

In [27]:
df['review'].unique()

array([nan, 'entity 약제 아님(진단명)', 'entity 주호소', 'entity 한국어',
       'entity 한국어(행위에 해당하는 entity가 한국어)', 'entity 약제 아님(진료과명)',
       'entity 약제 아님(meas_value)'], dtype=object)

In [28]:
df = df[df['review'].isna()]
df

,domain_id,source_value,concept_id,review
0,Condition,Esophageal varix without bleeding,22340,NaN
1,Condition,Chronic tonsillitis,23220,NaN
2,Condition,Neck pain,24134,NaN
3,Condition,Hypoglycemia,24609,NaN
4,Condition,acute tonsilitis,24660,NaN
...,...,...,...,...
3146,Drug,Midazolam 5mg/5mL inj,46287620,NaN
3147,Drug,Trestan* cap,2001000036,NaN
3148,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN
3149,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN
3150,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN

In [32]:
print(len(df[df['domain_id'] == 'Condition']))
print(len(df[df['domain_id'] == 'Drug']))
print(len(df[df['domain_id'] == 'Procedure']))
print(len(df[df['domain_id'] == 'Measurement']))

1578
981
378
110

In [33]:
from tqdm import tqdm
from src.MapOMOP.elasticsearch_client import ElasticsearchClient

# Elasticsearch 클라이언트 생성
es_client = ElasticsearchClient.create_default()

# concept_id로 concept_name 조회 (중복 제거해 한 번만 조회)
unique_ids = df["concept_id"].dropna().unique()
print(f"고유 concept_id: {len(unique_ids)}건")

id_to_name = {}
for cid in tqdm(unique_ids, desc="Fetching concept_name"):
    query_body = {
        "query": {"term": {"concept_id": str(cid)}},  # keyword 타입이므로 str 사용
        "_source": ["concept_name"],
        "size": 1
    }
    try:
        response = es_client.es_client.search(index="concept-small", body=query_body)
        hits = response["hits"]["hits"]
        if hits:
            id_to_name[cid] = hits[0]["_source"].get("concept_name")
        else:
            id_to_name[cid] = None
    except Exception as e:
        print(f"오류 (concept_id: {cid}): {e}")
        id_to_name[cid] = None

# 마지막 열 옆에 concept_name 추가
df["concept_name"] = df["concept_id"].map(id_to_name)
print(f"매핑 완료. 실패: {df['concept_name'].isna().sum()}건")
df.head()

고유 concept_id: 2873건

Fetching concept_name: 100%|██████████| 2873/2873 [00:31<00:00, 90.31it/s]

매핑 완료. 실패: 4건

,domain_id,source_value,concept_id,review,concept_name
0,Condition,Esophageal varix without bleeding,22340,NaN,esophageal varices without bleeding
1,Condition,Chronic tonsillitis,23220,NaN,chronic tonsillitis
2,Condition,Neck pain,24134,NaN,neck pain
3,Condition,Hypoglycemia,24609,NaN,hypoglycemia
4,Condition,acute tonsilitis,24660,NaN,acute tonsillitis

In [35]:
df[df['concept_name'].isna()]

,domain_id,source_value,concept_id,review,concept_name
3147,Drug,Trestan* cap,2001000036,NaN,None
3148,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN,None
3149,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN,None
3150,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN,None

In [38]:
df = df.drop(columns=['review'])
df

,domain_id,source_value,concept_id,concept_name
0,Condition,Esophageal varix without bleeding,22340,esophageal varices without bleeding
1,Condition,Chronic tonsillitis,23220,chronic tonsillitis
2,Condition,Neck pain,24134,neck pain
3,Condition,Hypoglycemia,24609,hypoglycemia
4,Condition,acute tonsilitis,24660,acute tonsillitis
...,...,...,...,...
3146,Drug,Midazolam 5mg/5mL inj,46287620,5 ml midazolam 1 mg/ml injection
3147,Drug,Trestan* cap,2001000036,None
3148,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,None
3149,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,None
3150,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,None

In [39]:
df.to_csv("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv", index=False)

In [1]:
import pandas as pd

main = pd.read_csv('/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv')
meas = pd.read_csv('/Users/rose/omop-mapper/data/snuh-baseline-meas.csv')

print(len(main[main['domain_id'] == 'Measurement']))
print(len(meas[meas['domain_id'] == 'Measurement']))

110
110

In [2]:
main = main[main['domain_id'] != 'Measurement']
main['domain_id'].unique()

array(['Condition', 'Drug', 'Procedure'], dtype=object)

In [3]:
main = pd.concat([main, meas], ignore_index=True)
main['domain_id'].unique()

array(['Condition', 'Drug', 'Procedure', 'Measurement'], dtype=object)

In [4]:
len(main[main['domain_id'] == 'Measurement'])

110

In [5]:
len(main)

3047

In [6]:
main.to_csv("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv")

In [8]:
main.to_excel("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.xlsx")

In [9]:
import pandas as pd

df = pd.read_excel("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.xlsx")
df

,no,domain_id,source_value,concept_id,concept_name
0,1,Condition,Esophageal varix without bleeding,22340,esophageal varices without bleeding
1,2,Condition,Chronic tonsillitis,23220,chronic tonsillitis
2,3,Condition,Neck pain,24134,neck pain
3,4,Condition,Hypoglycemia,24609,hypoglycemia
4,5,Condition,acute tonsilitis,24660,acute tonsillitis
...,...,...,...,...,...
3042,3043,Measurement,MAP,42527086,mean airway pressure
3043,3044,Measurement,minute volume,42527121,inspired minute volume during mechanical venti...
3044,3045,Measurement,Ambulatory systolic blood pressure,44789315,ambulatory systolic blood pressure
3045,3046,Measurement,Ambulatory diastolic blood pressure,44789316,ambulatory diastolic blood pressure
3046,3047,Measurement,epidermal growth factor receptor(Modification ...,46236952,glomerular filtration rate [volume rate/area] ...

In [10]:
df.to_csv("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv", index=False)

In [ ]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv')
df[df['domain_id'] == 'Procedure']

,no,domain_id,source_value,concept_id,concept_name
925,926,Procedure,Femur Both Lat,4003642,"radiologic examination of femur, anteroposteri..."
926,927,Procedure,Femur Lt AP,4003642,"radiologic examination of femur, anteroposteri..."
928,929,Procedure,Closed [endoscopic] biopsy of stomach,4004241,endoscopic biopsy of stomach
942,943,Procedure,Endoscopy of nasal sinus,4010253,nasal sinus endoscopy
943,944,Procedure,Sinus Endoscopy,4010253,nasal sinus endoscopy
...,...,...,...,...,...
2910,2911,Procedure,SONO Doppler AVF,46271896,doppler ultrasonography of arteriovenous fistula
2911,2912,Procedure,SONO Neck Except Thyroid/Parathyroid + Doppler,46272793,doppler ultrasonography of vascular structure ...
2934,2935,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN
2935,2936,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN
2936,2937,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN

In [5]:
remove_df = pd.read_csv("/Users/rose/omop-mapper/data/remove.csv")
if 'Entity Name' in remove_df.columns:
    to_remove = remove_df['Entity Name'].dropna().astype(str).unique()
    mask = ~( (df['domain_id'] == 'Procedure') & (df['source_value'].astype(str).isin(to_remove)) )
    df = df[mask]

In [6]:
df[df['domain_id'] == 'Procedure']

,no,domain_id,source_value,concept_id,concept_name
925,926,Procedure,Femur Both Lat,4003642,"radiologic examination of femur, anteroposteri..."
928,929,Procedure,Closed [endoscopic] biopsy of stomach,4004241,endoscopic biopsy of stomach
942,943,Procedure,Endoscopy of nasal sinus,4010253,nasal sinus endoscopy
945,946,Procedure,FILM SCAN - MRI,4013636,magnetic resonance imaging
946,947,Procedure,Chest Both Lat(Heart),4013637,"diagnostic radiography of chest, lateral"
...,...,...,...,...,...
2891,2892,Procedure,MRI Brain + Brain MRA + CE- MRA (contrast),45765683,magnetic resonance angiography of head with co...
2893,2894,Procedure,MRI Brain + Brain MRA + Carotid MRA (contrast),45765719,mr angiography of head and neck with contrast
2908,2909,Procedure,Myocardial SPECT (Pre-CABG Stress/Rest),46271428,single photon emission computed tomography of ...
2910,2911,Procedure,SONO Doppler AVF,46271896,doppler ultrasonography of arteriovenous fistula
2911,2912,Procedure,SONO Neck Except Thyroid/Parathyroid + Doppler,46272793,doppler ultrasonography of vascular structure ...

In [13]:
mask = (df['domain_id'] == 'Procedure') & (df['concept_id'] == 45763923)
indices = df[mask].index

if len(indices) >= 2:
    df.loc[indices[0], 'source_value'] = 'Neuropsychiatric Inventory Questionnaire'
    df.loc[indices[1], 'source_value'] = 'Neuropsychiatric Inventory – Nursing Home'

df[mask]  # Show the modified rows

,no,domain_id,source_value,concept_id,concept_name
2886,2887,Procedure,Neuropsychiatric Inventory Questionnaire,45763923,assessment of psychotic and behavioral symptom...
2887,2888,Procedure,Neuropsychiatric Inventory – Nursing Home,45763923,assessment of psychotic and behavioral symptom...

In [41]:
mask = df['source_value'] == '액상자궁경부세포검사(부인과PAP)'
df.loc[mask, 'source_value'] = 'LBC, Liquid-Based Cytology PAP'

In [44]:
import re

def remove_korean(text):
    return re.sub(r'[가-힣]', '', str(text))

mask_korean = df['source_value'].astype(str).str.contains('[가-힣]', regex=True)
df.loc[mask_korean, 'source_value'] = df.loc[mask_korean, 'source_value'].apply(remove_korean)

In [45]:
import re

# source_value 열에 한글이 포함된 행 추출
mask = df['source_value'].astype(str).str.contains('[가-힣]', regex=True)
df_korean = df[mask]

In [49]:
print(len(df[df['domain_id'] == 'Condition']))
print(len(df[df['domain_id'] == 'Drug']))
print(len(df[df['domain_id'] == 'Procedure']))
print(len(df[df['domain_id'] == 'Measurement']))

1578
981
237
110

In [50]:
df['no'] = range(1, len(df) + 1)
df

,no,domain_id,source_value,concept_id,concept_name
0,1,Condition,Esophageal varix without bleeding,22340,esophageal varices without bleeding
1,2,Condition,Chronic tonsillitis,23220,chronic tonsillitis
2,3,Condition,Neck pain,24134,neck pain
3,4,Condition,Hypoglycemia,24609,hypoglycemia
4,5,Condition,acute tonsilitis,24660,acute tonsillitis
...,...,...,...,...,...
3042,2902,Measurement,MAP,42527086,mean airway pressure
3043,2903,Measurement,minute volume,42527121,inspired minute volume during mechanical venti...
3044,2904,Measurement,Ambulatory systolic blood pressure,44789315,ambulatory systolic blood pressure
3045,2905,Measurement,Ambulatory diastolic blood pressure,44789316,ambulatory diastolic blood pressure
3046,2906,Measurement,epidermal growth factor receptor(Modification ...,46236952,glomerular filtration rate [volume rate/area] ...

In [51]:
df.to_excel("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.xlsx")
df.to_csv("/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv", index=False)

## Baseline_snomed

In [40]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/MapOMOP_evaluation_2_benchmark_1000.csv')
df

,Unnamed: 0,Test Index,Baseline,ID,Entity Name,Input Domain,Ground Truth Concept ID,Ground Truth Concept Name,Success,Mapping Correct,Best Result Domain,Best Concept ID,Best Concept Name,Best Score,Stage1 Candidates,Stage2 Candidates,Stage3 Candidates
0,1,10118,0,12985376-DS-217,___. <br> ## ? o,Condition,438130,harmful pattern of use of opioid,성공,오답,Condition,4302223.0,fracture of bone of head,4.0,1. [semantic] barotitis interna (ID: 4053304)\...,1. [semantic] ✓ barotitis interna (ID: 4053304...,1. [lexical] fracture of bone of head (ID: 430...
1,2,9909,0,12730675-DS-12,".5 F, vo",Condition,441408,vomiting,성공,오답,Condition,4203311.0,f factor,0.0,1. [semantic] single-domain antibodies (ID: 19...,1. [lexical] ✓ f factor (ID: 4203311)\r\n St...,1. [lexical] f factor (ID: 4203311)\r\n 최종: ...
2,3,7,1,10043750-DS-6,cecal cancer,Condition,443391,malignant tumor of cecum,성공,정답,Condition,443391.0,malignant tumor of cecum,5.0,1. [lexical] malignant tumor of cecum (ID: 443...,1. [lexical] ✓ malignant tumor of cecum (ID: 4...,1. [lexical] malignant tumor of cecum (ID: 443...
3,4,8466,1,11714071-DS-56,"""hole in her heart""",Condition,4289309,atrial septal defect,성공,오답,Condition,318549.0,cardiac septal defects,5.0,1. [lexical] hole in heart (ID: 45907830)\r\n ...,1. [semantic] ✓ perforation of cardiac device ...,1. [lexical] cardiac septal defects (ID: 31854...
4,5,12,1,10043750-DS-6,sciatica,Condition,372409,sciatica,성공,정답,Condition,372409.0,sciatica,5.0,1. [semantic] sciatica (ID: 45525972)\r\n ES...,1. [semantic] → sciatica (ID: 372409)\r\n St...,1. [semantic] sciatica (ID: 372409)\r\n 최종: ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2022,1,11392990-DS-6,calcified granulomas,Observation,4168134,calcified granuloma,성공,정답,Observation,4168134.0,calcified granuloma,5.0,1. [semantic] calcified granuloma (ID: 3428754...,1. [semantic] ✓ calcified granuloma (ID: 41681...,1. [semantic] calcified granuloma (ID: 4168134...
996,997,632,5,10839721-DS-9,atus: Ambulatory - Indep,Observation,4013697,independent walking,성공,오답,Meas Value,4114508.0,ambulatory,5.0,1. [semantic] ambulatory (ID: 3391113)\r\n E...,"1. [semantic] ✓ companion care, adult (e.g., i...",1. [semantic] ambulatory (ID: 4114508)\r\n 최...
997,998,2059,1,11392990-DS-6,thrombi,Observation,4245118,thrombus,성공,정답,Observation,4245118.0,thrombus,5.0,1. [lexical] thrombus (ID: 37546702)\r\n ES점...,1. [semantic] ✓ thrombus (ID: 4245118)\r\n S...,1. [semantic] thrombus (ID: 4245118)\r\n 최종:...
998,999,2061,1,11392990-DS-6,wall motion are normal,Observation,4158574,normal ventricular wall motion,성공,정답,Observation,4158574.0,normal ventricular wall motion,5.0,1. [lexical] normal ventricular wall motion (I...,1. [lexical] ✓ normal ventricular wall motion ...,1. [lexical] normal ventricular wall motion (I...
999,1000,2081,1,11392990-DS-6,atherosclerosis,Observation,4306703,atherosclerosis (morphologic abnormality),성공,정답,Observation,4306703.0,atherosclerosis,5.0,1. [semantic] atherosclerosis (ID: 45527027)\r...,1. [semantic] ✓ atherosclerosis (ID: 4306703)\...,1. [semantic] atherosclerosis (ID: 4306703)\r\...

In [42]:
df = df.drop(columns=['Unnamed: 0', 'Success', 'Mapping Correct', 'Best Result Domain', 'Best Concept ID', 'Best Concept Name',
                'Best Score', 'Stage1 Candidates', 'Stage2 Candidates', 'Stage3 Candidates'])
df

,Test Index,Baseline,ID,Entity Name,Input Domain,Ground Truth Concept ID,Ground Truth Concept Name
0,10118,0,12985376-DS-217,___. <br> ## ? o,Condition,438130,harmful pattern of use of opioid
1,9909,0,12730675-DS-12,".5 F, vo",Condition,441408,vomiting
2,7,1,10043750-DS-6,cecal cancer,Condition,443391,malignant tumor of cecum
3,8466,1,11714071-DS-56,"""hole in her heart""",Condition,4289309,atrial septal defect
4,12,1,10043750-DS-6,sciatica,Condition,372409,sciatica
...,...,...,...,...,...,...,...
995,2022,1,11392990-DS-6,calcified granulomas,Observation,4168134,calcified granuloma
996,632,5,10839721-DS-9,atus: Ambulatory - Indep,Observation,4013697,independent walking
997,2059,1,11392990-DS-6,thrombi,Observation,4245118,thrombus
998,2061,1,11392990-DS-6,wall motion are normal,Observation,4158574,normal ventricular wall motion
999,2081,1,11392990-DS-6,atherosclerosis,Observation,4306703,atherosclerosis (morphologic abnormality)

In [43]:
df = df.rename(columns={'Test Index': 'test_index',
                        'Baseline': 'baseline',
                        'ID': 'note_id',
                        'Entity Name': 'entity_name',
                        'Input Domain': 'domain_id',
                        'Ground Truth Concept ID': 'concept_id',
                        'Ground Truth Concept Name': 'concept_name'})
df

,test_index,baseline,note_id,entity_name,domain_id,concept_id,concept_name
0,10118,0,12985376-DS-217,___. <br> ## ? o,Condition,438130,harmful pattern of use of opioid
1,9909,0,12730675-DS-12,".5 F, vo",Condition,441408,vomiting
2,7,1,10043750-DS-6,cecal cancer,Condition,443391,malignant tumor of cecum
3,8466,1,11714071-DS-56,"""hole in her heart""",Condition,4289309,atrial septal defect
4,12,1,10043750-DS-6,sciatica,Condition,372409,sciatica
...,...,...,...,...,...,...,...
995,2022,1,11392990-DS-6,calcified granulomas,Observation,4168134,calcified granuloma
996,632,5,10839721-DS-9,atus: Ambulatory - Indep,Observation,4013697,independent walking
997,2059,1,11392990-DS-6,thrombi,Observation,4245118,thrombus
998,2061,1,11392990-DS-6,wall motion are normal,Observation,4158574,normal ventricular wall motion
999,2081,1,11392990-DS-6,atherosclerosis,Observation,4306703,atherosclerosis (morphologic abnormality)

In [45]:
print(len(df[df['domain_id'] == 'Condition']))
print(len(df[df['domain_id'] == 'Observation']))
print(len(df[df['domain_id'] == 'Procedure']))
print(len(df[df['domain_id'] == 'Measurement']))

250
250
250
250

In [44]:
df.to_csv("/Users/rose/omop-mapper/data/snomed-mapping-data-1000.csv", index=False)

In [46]:
import pandas as pd

df = pd.read_csv('/Users/rose/omop-mapper/data/snuh-baseline-mapping-data.csv')
df

,domain_id,source_value,concept_id,concept_name
0,Condition,Esophageal varix without bleeding,22340,esophageal varices without bleeding
1,Condition,Chronic tonsillitis,23220,chronic tonsillitis
2,Condition,Neck pain,24134,neck pain
3,Condition,Hypoglycemia,24609,hypoglycemia
4,Condition,acute tonsilitis,24660,acute tonsillitis
...,...,...,...,...
3042,Drug,Midazolam 5mg/5mL inj,46287620,5 ml midazolam 1 mg/ml injection
3043,Drug,Trestan* cap,2001000036,NaN
3044,Procedure,Leukocyte depleted platelet (400ml)-Filter오더필요,2001000106,NaN
3045,Procedure,Pre-storage Leukocyte depleted RBC (400ml),2001000107,NaN
3046,Procedure,Plateletpheresis (Leukocyte-depleted)-5일보관,2001000109,NaN

In [47]:
dup_count = df[df['domain_id'] == 'Procedure']['concept_id'].unique()
print(len(dup_count))

235